//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNode
    {
        public int nodeId { get; set; }
        public string nodeName { get; set; }
        public int parentNodeId { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
    }
}
